### ISSUE TITLE
[feature request] Add sidenotes support

### ISSUE THREAD

**Issue by cs-mshah** [faroukx/Obsidian-shiba-inu-theme#2]
It would be really nice to have sidenotes support as in the [obsidian sanctum theme](https://github.com/jdanielmourao/obsidian-sanctum/blob/main/documentation/Theme_Guide.md#:~:text=com/%20%3C/cite%3E-,%3Caside%3E,-%2D%20the%20aside%20element) ([css snippet](https://github.com/jdanielmourao/obsidian-sanctum/blob/main/src/scss/features/asides.scss)).

**Comment by faroukx** [comment]
Hi there, I would recommend using only the CSS snippet as it may not be possible to get permission from the creator of Sanctum since they seem to be inactive.
