### ISSUE TITLE
Unable install on Mobile device

### ISSUE THREAD

**Issue by Meemonomon** [faroukx/Obsidian-shiba-inu-theme#3]
Can't install it on my Android. 
It says : "No appropriate version found".
My device is : Redmi Note 10s

**Comment by faroukx** [comment]
Hello, could you provide more specific details?

**Comment by faroukx** [comment]
Hi! 

Unfortunately, I haven't received a response to my question, so I regret to inform you that I'll have to close the issue. Please don't hesitate to reach out if you need further assistance or have any other questions. Thanks!
