### ISSUE TITLE
とても素敵なテーマをありがとうございます！ 😜👍 改善のための提案は次のとおりです。 次のようなマークダウン要素のスタイルは、より美しく設計する必要があります。

### ISSUE THREAD

**Issue by zhouxinghong** [faroukx/Obsidian-shiba-inu-theme#5]
とても素敵なテーマをありがとうございます！ 😜👍
改善のための提案は次のとおりです。
次のようなマークダウン要素のスタイルは、より美しく設計する必要があります。

```html
> [!注]
> 仮想マシンの最大の利点は、異なるシステム プラットフォームで一貫した機能を実現できるため、仮想マシン環境で開発されたアプリケーションはすべて移植可能であることです。

> [!ヒント]
> 仮想マシンの最大の利点は、異なるシステム プラットフォームで一貫した機能を実現できるため、仮想マシン環境で開発されたアプリケーションはすべて移植可能であることです。

> [!警告]
> 仮想マシンの最大の利点は、異なるシステム プラットフォームで一貫した機能を実現できるため、仮想マシン環境で開発されたアプリケーションはすべて移植可能であることです。
```
![2023-03-05_224503](https://user-images.githubusercontent.com/54253524/222967508-cc487a8a-67d5-4700-8af3-08e6ae34911b.png)

次のバージョンでスタイルの外観を改善できることを願っています。 . . お題ありがとうございます！ 🤞👍

環境：Win10
バージョン: 1.0.7

**Comment by faroukx** [comment]
コメントをお寄せいただきありがとうございます。建設的なご意見、テーマ改善のためのご提案をお待ちしております。テーマ全体を楽しんでいただけたとのことで、光栄に思います。

吹き出しのスタイルについては、コミュニティプラグインストアで販売している「Style Settings」プラグインを使用すると簡単に変更することができます。このプラグインは、テーマを自分好みにカスタマイズするのに便利なプラグインです。

現在の吹き出しはObsidianのバニラバージョンですが、テーマの吹き出しである「柴犬」に変更するというご提案は興味深いですね。スタイル設定プラグインを使用していないユーザーのために、柴犬のコールアウトをデフォルトのコールアウトとして追加するよう努力します。次回のテーマアップデートでは、このご指摘を考慮し、お客様のご要望にお応えできるよう努力いたします。😊👍

改めて、建設的なフィードバックとサポートに感謝いたします。現在のテーマを十分にご理解いただけると幸いです。また、ご意見・ご質問等ございましたら、ご遠慮なくお問い合わせください。😊

また、柴犬が提供するバニラキャプションの代わりに、以下のキャプションを使用することができます：
![callouts](https://user-images.githubusercontent.com/109313204/222971829-f40bdc21-7c26-4cb5-9523-864e8a3addf6.png)

**Comment by zhouxinghong** [comment]
こんにちは！ 👍よろしくお願いします😜
私が上で説明したことは、あなたが今言ったことです。見てください：
```html
> [!NOTE] Title
> Contents
```

-------------------------------------------------- -------------------------------------------------- ---
さらに、UI のフォント スタイルが統一されていないという問題も発見しました。
これがバグなのか、デフォルトの動作なのかはわかりません。デモをご覧ください。
![2023-03-06_1](https://user-images.githubusercontent.com/54253524/222992592-c9662893-b2f9-499e-ad30-8e7f6f4195fc.png)

![2023-03-06_2](https://user-images.githubusercontent.com/54253524/222992463-f3992833-e1dc-4b89-b8fd-dc9a0608aaff.png)

1. まず、デフォルトのテーマを使用し、それらのフォント スタイルは一貫しています。
2. [柴犬] テーマに再度切り替えた後、UI のフォント スタイルが統一されていません。 赤い範囲ボックスと数字 1、2 で印を付けました。 事前にグローバル UI フォント スタイルをカスタマイズしたため、現在のパフォーマンス結果は満足のいくものではありません。 UI フォント スタイルがユーザーのカスタム アイデアに従うことができれば、このテーマはより完璧になります! とても素敵なテーマをありがとうございました！ 👍👍

**Comment by faroukx** [comment]
こんにちは！

詳細な回答ありがとうございます。確かに、それは私が解決する非常に良い指摘です。私たちは皆、異なる好みを持っているため、各ユーザーが自分自身のフォントを選択できるようにすることが重要です。問題を解決するために対応いたします。👍

あなたからのメッセージと、ユーザーエクスペリエンスの改善に対するあなたの貢献に感謝します。多くのユーザーにとって役立つと確信しています。

再度、ありがとうございました。またお会いしましょう！

**Comment by faroukx** [comment]
スタイル設定に、フォントの種類もサイズに加えてお好みで変更できるオプションを追加しました！😃

![Screenshot 2023-03-06 at 21 03 36](https://user-images.githubusercontent.com/109313204/223300386-075b912c-76f0-4095-8889-2aa197bc3b48.png)

**Comment by zhouxinghong** [comment]
ありがとう！ 😜 このデザイン最高！ 👍
