### ISSUE TITLE
Incorrect display of “quote” callout

### ISSUE THREAD

**Issue by Dirtyuri** [faroukx/Obsidian-shiba-inu-theme#6]
**Screenshots**
![S2G Callout Display in Shiba Inu](https://user-images.githubusercontent.com/68465099/232262718-af28ce20-f50e-4444-b28c-cd9af4e9aa24.gif)

**Desktop (please complete the following information):**
 - OS: win11

**Comment by faroukx** [comment]
Hey there,
To make things easier for everyone, I've decided to remove the feature and instead give you the option to turn it on or off in the style settings. I hope this makes things more user-friendly for you!

**Comment by faroukx** [comment]
Fixed!

![calloutquote](https://user-images.githubusercontent.com/109313204/233160230-e6288cf8-dba8-4fc0-9f71-3c6ed3345937.gif)

> To use the custom !quote callout, simply type your quote after the command. The first line and subsequent lines of the quote will automatically be formatted in italic. The last line, which should include the author's name, will be displayed in yellow on the right side of the quote.
